name: azd - Provision and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write      # OIDC login to Azure
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Azure CLI and log in via OIDC
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:      ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Install Azure Developer CLI - Updated to correct version
      - name: Install azd
        uses: Azure/setup-azd@v2
        with:
          version: latest

      # Ensure PNPM is present because the frontend pre-package hook uses it
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      # Provision + deploy the whole stack in one go
      - name: azd deploy
        run: |
          azd config set alpha.rollout true                # optional but faster on updates
          azd deploy --no-prompt --environment prod
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
